/*---Copyright by: Matthias Zubke, 75196 Remchingen, Germany--*/
var langLabel = [
{ //english
  "vHome": "Home",
  "vInput": "Input",
  "vHelp": "Help",
  "vEvaluation": "Evaluation",
  "vBack": "Back",
  "vTraining": "Training",
  "vOptions": "Options",
  "vGoalDay": "Goal of day:",
  "vGoalWeek": "Goal of week:",
  "vEmergency": "Emergency",
  "vAmount": "Amount of units",
  "vInsulinMeasure": "Insulin measurement",
  "vNeverDrinkAlc": "I never drink alcohol",
  "vLanguage": "Language",
  "vDeutsch": "Deutsch",
  "vEnglish": "english",
  "vLastMeal": "Last meal",
  "vMeal": "Meal",
  "vDrink": "Drink",
  "vDrinking": "Drinking",
  "vFruit": "Fruit",
  "vVegetable": "Vegetable",
  "vExercize": "Exercize",
  "vMedicine": "Medicine",
  "vBloodPressure": "Blood pressure",
  "vBloodSugar": "Blood sugar",
  "vInsulin": "Insulin",
  "vDailynote": "Daily note",
  "vWeight": "Weight",
  "vCompleteDay": "Complete the day",
  "vSelectMealType": "Select type of meal",
  "vFastlane": "Fastlane",
  "vBBreakfast": "Before breakfast",
  "vBreakfast": "Breakfast",
  "vABreakfast": "After breakfast",
  "vLunch": "Lunch",
  "vALunch": "After lunch",
  "vDinner": "Dinner",
  "vADinner": "After dinner",
  "vMealHistory": "Meal history",
  "vWeightRecord": "Weight recording",
  "vInputWeight": "Input weight",
  "vRoundedTo": "Rounded to",
  "vLastWeight": "Last weight",
  "vNewWeight": "New weight, filtered to max. 0,5kg difference",
  "vTable": "Table",
  "vChart": "Chart",
  "vWeek": "Week",
  "vMoreAThis": "More about this..",
  "vMore": "Want to know more!",
  "vMo": "Mo.",
  "vTu": "Tu.",
  "vWe": "We.",
  "vTh": "Th.",
  "vFr": "Fr.",
  "vSa": "Sa.",
  "vSu": "Su.",
  "vResult": "Result",
  "vOwnResult": "Own result",
  "vNumberProblems": "Number of Problems",
  "vNumberBinge": "Number of binge eating",
  "vNumberUrges": "Number urges",
  "vPhysHung": "Physical Hunger??",
  "vEnjoyFood": "Enjoy food??",
  "vStopFull": "Stopp when full??",
  "vTextGoalWeek": "Text goal of the week",
  "vHealthyFood": "Healthy??",
  "vMonday": "Monday",
  "vTuesday": "Tuesday",
  "vWednesday": "Wednesday",
  "vThursday": "Thursday",
  "vFriday": "Friday",
  "vSaturday": "Saturday",
  "vSunday": "Sunday",
  "vNumber": "Number"
},
{ //German
	"vHome": "Home",
	"vInput": "Eingabe",
	"vHelp": "Hilfe",
	"vEvaluation": "Auswertung",
	"vBack": "Zurück",
	"vTraining": "Training",
	"vOptions": "Einstellungen",
	"vGoalDay": "Tagesziel:",
	"vGoalWeek": "Wochenziel:",
	"vEmergency": "Notfall",
	"vAmount": "Anzahl Einheiten",
	"vInsulinMeasure": "Insulin Messungen",
	"vNeverDrinkAlc": "Ich trinke nie Alkohol",
	"vLanguage": "Sprache",
	"vDeutsch": "Deutsch",
	"vEnglish": "English",
	"vLastMeal": "Letzte Mahlzeit",
	"vMeal": "Mahlzeit",
	"vDrink": "Getränk",
	"vDrinking": "Trinken",
	"vFruit": "Obst",
	"vVegetable": "Gemüse",
	"vExercize": "Bewegung",
	"vMedicine": "Medikamente",
	"vBloodPressure": "Blutdruck",
	"vBloodSugar": "Blutzuckermessung",
	"vInsulin": "Insulin",
	"vDailynote": "Tagesnotiz",
	"vWeight": "Gewicht",
	"vCompleteDay": "Tag abschließen",
	"vSelectMealType": "Angabe der Mahlzeit",
	"vFastlane": "Schnelldurchgang",
	"vBBreakfast": "Vor Frühstück",
	"vBreakfast": "Frühstück",
	"vABreakfast": "Nach Frühstück",
	"vLunch": "Mittagessen",
	"vALunch": "Nach Mittagessen",
	"vDinner": "Abendessen",
	"vADinner": "Nach Abendessen",
	"vMealHistory": "Eingegebene Mahlzeiten",
	"vWeightRecord": "Gewichtserfassung",
	"vInputWeight": "Gewogen",
	"vRoundedTo": "Gerundet",
	"vLastWeight": "Letztes Gewicht",
	"vNewWeight": "Neues Gewicht, gefiltert auf maximal 0,5kg Differenz",
	"vTable": "Tabelle",
	"vChart": "Grafik",
	"vWeek": "Woche",
	"vMoreAThis": "Mehr darüber..",
	"vMore": "Ich will mehr wissen!",
	"vMo": "Mo.",
	"vTu": "Di.",
	"vWe": "Mi.",
	"vTh": "Do.",
	"vFr": "Fr.",
	"vSa": "Sa.",
	"vSu": "So.",
	"vResult": "Bewertung",
	"vOwnResult": "Eigenbewertung",
	"vNumberProblems": "Anzahl Probleme",
	"vNumberBinge": "Anzahl Essattacken",
	"vNumberUrges": "Anzahl Heißhunger",
	"vPhysHung": "Körperlicher Hunger",
	"vEnjoyFood": "Genuss",
	"vStopFull": "Aufhören wenn satt",
	"vTextGoalWeek": "Text Wochenziel",
	"vHealthyFood": "Ausgewogene Ernährung",
	"vMonday": "Montag",
	"vTuesday": "Dienstag",
	"vWednesday": "Mittwoch",
	"vThursday": "Donnerstag",
	"vFriday": "Freitag",
	"vSaturday": "Samstag",
	"vSunday": "Sonntag",
	"vNumber": "Nummer"
} 
]